import type { Metadata } from "next";
import { Oswald } from "next/font/google";
import "./globals.css";
import Header from "./_components/header/Header";

const oswald = Oswald({
  variable: "--font-Oswald",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="cs">
      <body className={`${oswald.variable} antialiased text-primary`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
